Feature: Create user feature

Scenario: Validación de campos vacios
    When I press "Skip"
    And I press "Register"
    And I enter text "jmauricio" into field with id "username"
    And I press "Register"
    Then I should see "Validation error"
    And I press "OK" 
Scenario: Email invalido
    When I press "Skip"
    And I press "Register"
    And I enter text "jmauricio123456" into field with id "username"
    And I enter text "jmauricio" into field with id "email"
    And I enter text "12345678" into field with id "password"
    And I enter text "12345678" into field with id "confirm_password"
    And I press "Register"
    Then I should see "invalid email address"
    And I press "OK" 
Scenario: Validar información de entrada de campo de usuario
    When I press "Skip"
    And I press "Register"
    And I enter text "##///@&()´" into field with id "username"
    And I enter text "123@h.com" into field with id "email"
    And I enter text "12345678" into field with id "password"
    And I enter text "12345678" into field with id "confirm_password"
    And I press "Register"
    Then I should see "Usernames can only contain letters"
    And I press "OK" 
Scenario: Validar longitud minima del password
    When I press "Skip"
    And I press "Register"
    And I enter text "jmauricio123" into field with id "username"
    And I enter text "jmauricio@mail.com" into field with id "email"
    And I enter text "12345" into field with id "password"
    And I enter text "12345" into field with id "confirm_password"
    And I press "Register"
    Then I should see "Your password has to be at least 8 characters long"
    And I press "OK" 
Scenario: Registro exitoso
    When I press "Skip"
    And I press "Register"
    And I enter text "jmauricio01234567" into field with id "username"
    And I enter text "jmauricio@mOaail.com" into field with id "email"
    And I enter text "1234567A@" into field with id "password"
    And I enter text "1234567A@" into field with id "confirm_password"
    And I press "Register"
    And I press "Next"
    And I press "Next"
    Then I should see "LET'S START!"
    And I press "LET'S START!"


